apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T12:12:10Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "19609"
  uid: 781015b3-e5fa-4c07-8c3b-682805b983bc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.151.218
  clusterIPs:
  - 10.100.151.218
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32683
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
