apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T13:25:43Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "544"
  uid: c49498a6-35a1-441c-8855-8e6df88b34f3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.206.148
  clusterIPs:
  - 10.98.206.148
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32711
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
